### ISSUE TITLE
Userstyles default style - categories/site browsing no screenshot styles only

### ISSUE THREAD

**Issue by the-j0k3r** [the-j0k3r/userstyles-inspired-dark#2]
* **Browser**: Any
* **Operating System**: Any
* **Screenshot/gif**:

![no screenshot bug](https://user-images.githubusercontent.com/31389848/40480119-6e324d4c-5f45-11e8-931f-8844d15bab8f.gif)

* **HTML of the section where the issue occurs**:

````html
<img src="/ui/images/no_screenshot.png" class="screenshot_img">
````

The selector in use is

```css
.screenshot_img {
	width: 220px;
	height: 131px;
	border-radius: 4px 4px 0 0;
	object-fit: cover;
}
```

That page uses `.screenshot_img_long` for the styles with screenshots :(

The portion below fixes this bug,  but breaks the vertical alignment in
normal long view ins pages like https://userstyles.org/styles/browse/recently-updated with long view

So Im not adding this fix for now. reference 3d150bf https://github.com/the-j0k3r/userstyles-inspired-dark/blob/3d150bf9536c7b793ddd13da77c7446c1613047a/userstyles-inspired-dark.css#L2535-L2572

```css
#title_long {
  margin-top: 40px !important;
}

.style_card_long {
	width: 728px !important;
	height: 131px !important;
	box-shadow: inset 0 -1px 0 0 #444 !important;
	padding: 21px 0px 21px 0px !important;
	display: flex !important;
	flex-direction: row !important;
	justify-content: space-between !important;
}

.screenshot_img_long {
	width: 220px !important;
	height: 131px !important;
	border-radius: 4px !important;
	object-fit: cover !important;
}
```

**Comment by the-j0k3r** [comment]
Actually never mind easy fix,

```css
.style_card_long .screenshot_img {
	width: 160px !important;
	height: 88px !important;
}
```

Done fix incoming after a much needed cup of coffee.
